# Generated by Django 2.1.3 on 2019-01-05 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('ADO_RUN', models.IntegerField(primary_key=True, serialize=False)),
                ('ADO_NOM', models.CharField(max_length=15)),
                ('ADO_APELL', models.CharField(max_length=15)),
                ('ADO_EDAD', models.IntegerField()),
                ('ADO_FONO', models.IntegerField()),
                ('ADO_MAIL', models.EmailField(max_length=30)),
                ('ADO_DIR', models.CharField(max_length=20)),
                ('ADO_USU', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
        ),
    ]
