# Generated by Django 2.1.3 on 2019-01-05 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desparasitacion', '0001_initial'),
        ('tipo_mas', '0001_initial'),
        ('genero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('MAS_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('MAS_NOM', models.CharField(max_length=15)),
                ('MAS_EDAD', models.IntegerField()),
                ('MAS_DES', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='desparasitacion.Desparasitacion')),
                ('MAS_GEN', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='genero.Genero')),
                ('MAS_TIPO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipo_mas.Tipo_Mas')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('VAC_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('VAC_NOM', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='MAS_VAC',
            field=models.ManyToManyField(to='mascota.Vacuna'),
        ),
    ]
