# Generated by Django 2.1.5 on 2019-01-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
