# Generated by Django 2.1.5 on 2019-01-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20190113_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='run',
            field=models.IntegerField(default=19135904, unique=True),
            preserve_default=False,
        ),
    ]
