# Generated by Django 2.1.5 on 2019-01-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20190113_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fono',
            field=models.IntegerField(null=True),
        ),
    ]
