# Generated by Django 2.1.5 on 2019-01-10 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablas_basicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='static/img/')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('desparasitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas_basicas.Desparasitacion')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas_basicas.Genero')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tablas_basicas.Tipo')),
                ('vacuna', models.ManyToManyField(blank=True, to='tablas_basicas.Vacuna')),
            ],
        ),
    ]
